@ReceiptVoucher.Server_HostAddress = https://localhost:7210



### ------------ User Controller -----------------------------------------


### GET All Users With Their Roles -------

GET {{ReceiptVoucher.Server_HostAddress}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiYTlhY2I5ODYtN2ZmMS00ZWMwLTk0ZWItZWVkOGNlZTRiNTViIiwiZW1haWwiOiJqb2huQGUiLCJ1aWQiOiI4NTcwNGZmNy0zMzYyLTRhMjctYjM2MS1kZTNlMTA5NDBmZGMiLCJyb2xlcyI6IkFkbWluIiwiZXhwIjoxNzA5NzUyMTUxLCJpc3MiOiJSZWNlaXB0Vm91Y2hlclNlcnZlciIsImF1ZCI6IlJlY2VpcHRWb3VjaGVyQ2xpZW50In0.dIbX1wtzY0YAHxuyi6RMYCayxFeR8Ws56av0V59L_LQ
###

### POST Create -------
POST {{ReceiptVoucher.Server_HostAddress}}/api/users
Content-Type: application/json

{
   "FirstName" : "ولي32",
  "LastName" : "3محمد",
  "UserName": "w@w3",
  "Email" : "w@w3",
  "BranchId" : 35,
  "Password" : "1234",
  "ConfirmPassword" : "1234",
  "Role" : {
      "RoleId" : "641c4c55-ab32-447c-affe-84423db03258",
      "RoleName" : "Gest",
      "IsSelected" : true
  }
}


### PUT Update User -----
PUT {{ReceiptVoucher.Server_HostAddress}}/api/users
Content-Type: application/json

{
  "UserId" : "225c1da8-b651-4863-acdb-f592988812ec",
  "FirstName" : "ولي32",
  "LastName" : "3محمد",
  "UserName": "w@w3",
  "Email" : "w@w3",
  "BranchId" : 20,
  "role" : {
      
      "RoleName" : "User"
    }
    
}

### Delete User -----

DELETE {{ReceiptVoucher.Server_HostAddress}}/api/users/20aa30a0-cef9-4e0d-b9a5-3ac63f45f23b




### Change Stuts Of User
POST {{ReceiptVoucher.Server_HostAddress}}/api/users/ChangeUserStatus/a6624342-8161-4b95-b4b5-90ad61dee3d3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiYTlhY2I5ODYtN2ZmMS00ZWMwLTk0ZWItZWVkOGNlZTRiNTViIiwiZW1haWwiOiJqb2huQGUiLCJ1aWQiOiI4NTcwNGZmNy0zMzYyLTRhMjctYjM2MS1kZTNlMTA5NDBmZGMiLCJyb2xlcyI6IkFkbWluIiwiZXhwIjoxNzA5NzUyMTUxLCJpc3MiOiJSZWNlaXB0Vm91Y2hlclNlcnZlciIsImF1ZCI6IlJlY2VpcHRWb3VjaGVyQ2xpZW50In0.dIbX1wtzY0YAHxuyi6RMYCayxFeR8Ws56av0V59L_LQ

###
### ---------------------------------------------------------------#END

GET {{ReceiptVoucher.Server_HostAddress}}/api/branches/GetAllAsync
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiZDdmOGIzMTQtYjJjMC00N2JmLWFlMmQtNTQ4YTBiYWQwYjQwIiwiZW1haWwiOiJqb2huQGUiLCJ1aWQiOiI4NTcwNGZmNy0zMzYyLTRhMjctYjM2MS1kZTNlMTA5NDBmZGMiLCJyb2xlcyI6IkFkbWluIiwiZXhwIjoxNzA4Mjg4Mjc0LCJpc3MiOiJSZWNlaXB0Vm91Y2hlclNlcnZlciIsImF1ZCI6IlJlY2VpcHRWb3VjaGVyQ2xpZW50In0.G-EIMei1371FHEaoMfFxcpOxQe9ROxo7-k5aCQ8fE_U

###

POST {{ReceiptVoucher.Server_HostAddress}}/api/branches/AddOneAsync
Content-Type: application/json

{
  //Branch
}

###

DELETE {{ReceiptVoucher.Server_HostAddress}}/api/branches?id=4

###

DELETE {{ReceiptVoucher.Server_HostAddress}}/api/branches?id=0

###

PUT {{ReceiptVoucher.Server_HostAddress}}/api/branches
Content-Type: application/json

{
  
   {
    "id": 12,
    "name": "77777المكتب7"
  }
}

###

GET {{ReceiptVoucher.Server_HostAddress}}/api/branches/GetAllAsync

###

POST {{ReceiptVoucher.Server_HostAddress}}/api/auth/register
Content-Type: application/json

{
  //RegisterModel
}

###

POST {{ReceiptVoucher.Server_HostAddress}}/api/auth/token
Content-Type: application/json

{
  //TokenRequestModel
}

###

POST {{ReceiptVoucher.Server_HostAddress}}/api/auth/AddRole
Content-Type: application/json

{
  //AddRoleModel
}

###

GET {{ReceiptVoucher.Server_HostAddress}}/api/projects/GetAllAsync

###

POST {{ReceiptVoucher.Server_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Gmail10",
  "lastName": "Gmail10",
  "userName": "Gmail10",
  "Email": "Gmail10",
  "password": "Gmail123!"
}

###

POST {{ReceiptVoucher.Server_HostAddress}}/api/auth/register
Content-Type: application/json

{
  //RegisterModel
}

###

POST {{ReceiptVoucher.Server_HostAddress}}/api/auth/register
Content-Type: application/json

{
  //RegisterModel
}

###

GET {{ReceiptVoucher.Server_HostAddress}}/api/branches/GetAllAsync

###

GET {{ReceiptVoucher.Server_HostAddress}}/api/users/api/users

###

POST {{ReceiptVoucher.Server_HostAddress}}/api/users/api/users
Content-Type: application/json

{
  "FirstName": "John",
  "LastName": "Doe",
  "Email": "johndoe@example.com",
  "UserName": "johndoe",
  "Password": "P@ssw0rd",
  "Roles": ["Role1"]
  
}

###

GET {{ReceiptVoucher.Server_HostAddress}}/api/users/users

###

GET {{ReceiptVoucher.Server_HostAddress}}/api/roles

###

GET {{ReceiptVoucher.Server_HostAddress}}/api/roles

###








POST {{ReceiptVoucher.Server_HostAddress}}/api/users/ChangeUserStatus/string

###

###

GET {{ReceiptVoucher.Server_HostAddress}}/api/users/GetUserDetails
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3YWxlZWQiLCJqdGkiOiIyZjlkZjQ5OS03MjNkLTRjNGEtYjU5Ni1kNzIzNDkwZTg0YTAiLCJlbWFpbCI6IndhbGVlZEBnbWFpbCIsInVpZCI6ImE2NjI0MzQyLTgxNjEtNGI5NS1iNGI1LTkwYWQ2MWRlZTNkMyIsInJvbGVzIjoiVXNlciIsImV4cCI6MTcxMDY3ODkzMCwiaXNzIjoiUmVjZWlwdFZvdWNoZXJTZXJ2ZXIiLCJhdWQiOiJSZWNlaXB0Vm91Y2hlckNsaWVudCJ9.xtwYsbYoLkBn5cg6GvGFwjHckb-oKC8-clWkSdemOjc
### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiOTFkZjlhYmUtYjUyOC00ZGM2LTg2YmQtNjBkMDkxMzIwMTc5IiwiZW1haWwiOiJqb2huQGUiLCJ1aWQiOiI4NTcwNGZmNy0zMzYyLTRhMjctYjM2MS1kZTNlMTA5NDBmZGMiLCJyb2xlcyI6IkFkbWluIiwiZXhwIjoxNzEwNjc2MzY5LCJpc3MiOiJSZWNlaXB0Vm91Y2hlclNlcnZlciIsImF1ZCI6IlJlY2VpcHRWb3VjaGVyQ2xpZW50In0.QCF7F24_UKF-cTewRUVMx7UuMhmCWmEO3x_eMBGECOA
###
