@ReceiptVoucher.Server_HostAddress = https://localhost:7210

GET {{ReceiptVoucher.Server_HostAddress}}/api/branches/GetAllAsync

###

POST {{ReceiptVoucher.Server_HostAddress}}/api/branches/AddOneAsync
Content-Type: application/json

{
  //Branch
}

###

DELETE {{ReceiptVoucher.Server_HostAddress}}/api/branches?id=4

###

DELETE {{ReceiptVoucher.Server_HostAddress}}/api/branches?id=0

###

PUT {{ReceiptVoucher.Server_HostAddress}}/api/branches
Content-Type: application/json

{
  
   {
    "id": 12,
    "name": "77777الفرع7"
  }
}

###

GET {{ReceiptVoucher.Server_HostAddress}}/api/branches/GetAllAsync

###
